name: e_fu
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-215.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: 1.3.1
  # permission_handler: ^10.2.0
  shared_preferences:
  flutter_easyloading:
  # paginated_search_bar: ^1.1.2
  http: ^0.13.5
  age_calculator: ^1.0.0
  syncfusion_flutter_gauges: ^21.1.41
  ele_progress: ^0.0.1
  table_calendar: ^3.0.9
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/images/home_outlined.png
      - assets/images/home.png
      - assets/images/e_user_outlined.png
      - assets/images/e_user.png
      - assets/images/f_user_outlined.png
      - assets/images/f_user.png
      
